// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriorAuth.API.Data;

#nullable disable

namespace PriorAuth.API.Migrations
{
    [DbContext(typeof(PriorAuthDbContext))]
    partial class PriorAuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriorAuth.API.Models.Authorization", b =>
                {
                    b.Property<int>("AuthorizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("authorization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuthorizationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("HealthPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("health_plan_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhysicianId")
                        .HasColumnType("text")
                        .HasColumnName("physician_id");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("primary_diagnosis");

                    b.Property<string>("Program")
                        .HasColumnType("text")
                        .HasColumnName("program");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("SiteId")
                        .HasColumnType("text")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AuthorizationId");

                    b.HasIndex("HealthPlanId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.HasIndex("PrimaryDiagnosis");

                    b.HasIndex("SiteId");

                    b.ToTable("authorizations");
                });

            modelBuilder.Entity("PriorAuth.API.Models.AuthorizationDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorizationId")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_id");

                    b.Property<string>("DiagnosisCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_code");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("DiagnosisCode");

                    b.ToTable("authorization_diagnoses");
                });

            modelBuilder.Entity("PriorAuth.API.Models.AuthorizationProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorizationId")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("procedure_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ProcedureCode");

                    b.ToTable("authorization_procedures");
                });

            modelBuilder.Entity("PriorAuth.API.Models.DiagnosisCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("diagnosis_codes");
                });

            modelBuilder.Entity("PriorAuth.API.Models.HealthPlan", b =>
                {
                    b.Property<int>("HealthPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("health_plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthPlanId"));

                    b.Property<string>("Entity")
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("InsPlanCode")
                        .HasColumnType("text")
                        .HasColumnName("ins_plan_code");

                    b.Property<string>("LineOfBusiness")
                        .HasColumnType("text")
                        .HasColumnName("line_of_business");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<string>("PlanType")
                        .HasColumnType("text")
                        .HasColumnName("plan_type");

                    b.HasKey("HealthPlanId");

                    b.ToTable("health_plans");
                });

            modelBuilder.Entity("PriorAuth.API.Models.Member", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("GroupNumber")
                        .HasColumnType("text")
                        .HasColumnName("group_number");

                    b.Property<string>("IpaCode")
                        .HasColumnType("text")
                        .HasColumnName("ipa_code");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MemberCode")
                        .HasColumnType("text")
                        .HasColumnName("member_code");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("PatientId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("PriorAuth.API.Models.ProcedureCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("procedure_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("procedure_codes");
                });

            modelBuilder.Entity("PriorAuth.API.Models.Provider", b =>
                {
                    b.Property<string>("PhysicianId")
                        .HasColumnType("text")
                        .HasColumnName("physician_id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text")
                        .HasColumnName("cell_phone");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("Fax")
                        .HasColumnType("text")
                        .HasColumnName("fax");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Npi")
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Specialty1")
                        .HasColumnType("text")
                        .HasColumnName("specialty1");

                    b.Property<string>("Specialty2")
                        .HasColumnType("text")
                        .HasColumnName("specialty2");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("PhysicianId");

                    b.ToTable("providers");
                });

            modelBuilder.Entity("PriorAuth.API.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasColumnType("text")
                        .HasColumnName("site_id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Fax")
                        .HasColumnType("text")
                        .HasColumnName("fax");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Npi")
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<bool>("Participating")
                        .HasColumnType("boolean")
                        .HasColumnName("participating");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Specialty1")
                        .HasColumnType("text")
                        .HasColumnName("specialty1");

                    b.Property<string>("Specialty2")
                        .HasColumnType("text")
                        .HasColumnName("specialty2");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("SteerageFlag")
                        .HasColumnType("text")
                        .HasColumnName("steerage_flag");

                    b.Property<string>("Tin")
                        .HasColumnType("text")
                        .HasColumnName("tin");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("SiteId");

                    b.ToTable("sites");
                });

            modelBuilder.Entity("PriorAuth.API.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorizationId")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.ToTable("status_history");
                });

            modelBuilder.Entity("PriorAuth.API.Models.Authorization", b =>
                {
                    b.HasOne("PriorAuth.API.Models.HealthPlan", "HealthPlan")
                        .WithMany()
                        .HasForeignKey("HealthPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriorAuth.API.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriorAuth.API.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriorAuth.API.Models.DiagnosisCode", "PrimaryDiagnosisCode")
                        .WithMany()
                        .HasForeignKey("PrimaryDiagnosis")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriorAuth.API.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HealthPlan");

                    b.Navigation("Member");

                    b.Navigation("PrimaryDiagnosisCode");

                    b.Navigation("Provider");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PriorAuth.API.Models.AuthorizationDiagnosis", b =>
                {
                    b.HasOne("PriorAuth.API.Models.Authorization", null)
                        .WithMany("Diagnoses")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriorAuth.API.Models.DiagnosisCode", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("PriorAuth.API.Models.AuthorizationProcedure", b =>
                {
                    b.HasOne("PriorAuth.API.Models.Authorization", null)
                        .WithMany("Procedures")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriorAuth.API.Models.ProcedureCode", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("PriorAuth.API.Models.StatusHistory", b =>
                {
                    b.HasOne("PriorAuth.API.Models.Authorization", "Authorization")
                        .WithMany()
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("PriorAuth.API.Models.Authorization", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
